name: 'Annotate uncovered changed lines'
description: 'Annotates changed lines in this pr that are not covered by tests'
inputs:
  github-token:
    description: github token for creating a commit status
  coverage-file:
    description: containing the coverage data in either istanbul or lcov format
  coverage-type:
    description: type of the coverage data - either 'istanbul' or 'lcov'. Default 'istanbul'.
    required: false
    default: 'istanbul'
  base-ref:
    description: base branch to which to merge
runs:
  using: 'node16'
  main: 'dist/index.js'
