name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
